{% set name = "sagemaker_pyspark" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ff15ef173eba79210289cffaef6c604ebb9cda89a59a5935748e3bcf8d8bd17

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python <3.8
    - pyspark >=2.3.2
    - numpy
    - pytest-runner
    - pypandoc
  run:
    - python <3.8
    - py4j
    - pyspark >=2.3.2

test:
  imports:
    - sagemaker_pyspark

about:
  home: https://github.com/aws/sagemaker-spark
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - licenses/LICENSE-hadoop.txt
    - licenses/LICENSE-htrace.txt
  summary: Amazon SageMaker PySpark Bindings
  dev_url: https://github.com/aws/sagemaker-spark

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
